# OpenAI API配置
openai_api_key: "your-api-key-here"
openai_api_base: "https://api.openai.com/v1"  # 可以配置为其他代理地址

# 视频文件目录
video_directory: "E:/迅雷下载/test"

# 需要从文件名中移除的字符串模式
remove_patterns:
  - "[1080p]"
  - "(Official)"
  - "720p"
  - "1080p"
  - "2160p"
  - "HD"
  - "[*]"

# 是否将英文文件名翻译成中文
translate_to_chinese: true

# 文件名最大长度
max_filename_length: 30 
